import Head from "next/head";
import Link from "next/link";
// import users from "../users/users.json";
import styles from "../styles/Home.module.css";
import { AddUserForms } from "../components/addUserForm";

export default function Home({ users }) {
  return (
    <>
      <Head>
        <title>Nodemailer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2> Home page </h2>
      <div className={styles.users}>
        {users.map((user) => {
          return (
            <Link
              className={styles.user}
              key={user.id}
              href={`/${user.organisation}`}>
              Contact To {user.email}
            </Link>
          );
        })}
      </div>
      <hr />
      <AddUserForms />
    </>
  );
}

export const getServerSideProps = async () => {
  const res = await fetch("http://localhost:8008/users");
  const users = await res.json();

  return {
    props: {
      users,
    },
  };
};
